---

- name: update apt cache
  apt: update_cache=yes

- name: Install common packages
  apt: name={{ item }} state=latest
  with_items:
    - xterm
    - bash-completion
    # add your favorite packages here...
